# Generated by Django 4.2.19 on 2025-02-21 13:09

from django.db import migrations, models
import games_display.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_address', models.TextField()),
                ('location_cityblock', models.IntegerField(choices=[(0, 'Donji grad'), (1, 'Gornji grad – Medveščak'), (2, 'Trnje'), (3, 'Maksimir'), (4, 'Peščenica – Žitnjak'), (5, 'Novi Zagreb – istok'), (6, 'Novi Zagreb – zapad'), (7, 'Trešnjevka – sjever'), (8, 'Trešnjevka – jug'), (9, 'Črnomerec'), (10, 'Gornja Dubrava'), (11, 'Donja Dubrava'), (12, 'Stenjevec'), (13, 'Podsused – Vrapče'), (14, 'Podsljeme'), (15, 'Sesvete'), (16, 'Brezovica')])),
                ('location_gps', models.JSONField(default=games_display.models.FutsalField.returnDictionary)),
            ],
        ),
    ]
