# Generated by Django 4.2.19 on 2025-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalfield',
            name='number_of_fields',
            field=models.IntegerField(default=1),
        ),
    ]
