# Generated by Django 4.2.19 on 2025-02-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_display', '0002_futsalfield_number_of_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_full', models.IntegerField()),
                ('players_missing', models.IntegerField()),
                ('custom_description', models.TextField()),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('play_time_start', models.DateTimeField()),
                ('play_time_end', models.TimeField()),
                ('field_number', models.IntegerField()),
                ('all_joining_players', models.ManyToManyField(related_name='joining_players', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_creator', to=settings.AUTH_USER_MODEL)),
                ('futsal_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games_display.futsalfield')),
            ],
        ),
    ]
