# Generated by Django 4.2.19 on 2025-02-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_display', '0003_futsalgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsalgame',
            name='field_number',
        ),
        migrations.AlterField(
            model_name='futsalgame',
            name='futsal_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_display.futsalfield'),
        ),
    ]
