# Generated by Django 4.2.19 on 2025-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_display', '0004_remove_futsalgame_field_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalgame',
            name='play_time_end',
            field=models.DateTimeField(),
        ),
    ]
