# Generated by Django 4.2.19 on 2025-03-02 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_display', '0005_alter_futsalgame_play_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalfield',
            name='location_cityblock',
            field=models.IntegerField(choices=[(0, 'Donji grad'), (1, 'Medveščak'), (2, 'Trnje'), (3, 'Maksimir'), (4, 'Žitnjak'), (5, 'Novi Zagreb – istok'), (6, 'Novi Zagreb – zapad'), (7, 'Trešnjevka – sjever'), (8, 'Trešnjevka – jug'), (9, 'Črnomerec'), (10, 'Gornja Dubrava'), (11, 'Donja Dubrava'), (12, 'Stenjevec'), (13, 'Podsused – Vrapče'), (14, 'Podsljeme'), (15, 'Sesvete'), (16, 'Brezovica')]),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('root_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games_display.futsalgame')),
            ],
        ),
    ]
