# Generated by Django 4.2.19 on 2025-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
    ]
