# Generated by Django 4.2.19 on 2025-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_remove_player_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(default='2000-10-10'),
        ),
    ]
