# Generated by Django 4.2.19 on 2025-02-25 23:42

from django.db import migrations
from cloudinary.models import CloudinaryField


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_player_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=CloudinaryField("image", overwrite=True)
        ),
    ]
